import { Metadata } from "next";
import { Archivo } from "next/font/google";
import Header from "@/components/utils/Header";
import "@/app/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const archivo = Archivo({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
