import { Metadata } from "next";
import { Archivo } from "next/font/google";
import "@/app/ui/globals.css";

import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { Suspense } from "react";
import NoteContextProvider from "@/contexts/NoteContextProvider";
import LabelContextProvider from "@/contexts/LabelContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const archivo = Archivo({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} antialiased`}>
        <Suspense>
          <LabelContextProvider>
            <NoteContextProvider>
              <SidebarProvider
                className="bg-neutral-200"
                style={
                  {
                    "--sidebar-width": "calc(var(--spacing) * 72)",
                    "--header-height": "calc(var(--spacing) * 12)",
                  } as React.CSSProperties
                }
              >
                <AppSidebar className="bg-violet-50" variant="inset" />
                <SidebarInset>
                  <SiteHeader />
                  <div className="py-5 lg:px-30">{children}</div>
                </SidebarInset>
              </SidebarProvider>
            </NoteContextProvider>
          </LabelContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
